spring:
  application:
    name: oauth2-spring-demo

  security:
    oauth2:
      client:
        registration:
          authorizationserver:
            client-name: OAuth2 Spring Demo Client
            client-id: oauth2-demo-client
            client-secret: oauth2-demo-secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          authorizationserver:
            issuer-uri: http://${SAS_HOST:auth.mydomain.com:8081}
            user-name-attribute: sub

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG